/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e3dfff',
        'primary-fixed': '#e4dfff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#fcf8ff',
        error: '#ba1a1a',
        surface: '#fcf8ff',
        'on-tertiary-container': '#e1ffec',
        background: '#fcf8ff',
        'on-primary': '#ffffff',
        primary: '#5341cd',
        'on-tertiary': '#ffffff',
        'surface-tint': '#5847d2',
        'tertiary-fixed': '#6ffbbe',
        'on-error-container': '#93000a',
        'secondary-container': '#fea619',
        'on-primary-container': '#faf6ff',
        'on-secondary-container': '#684000',
        outline: '#787586',
        'on-tertiary-fixed': '#002113',
        'on-background': '#1a1931',
        'on-surface-variant': '#474554',
        'inverse-on-surface': '#f2eeff',
        'inverse-surface': '#2f2e47',
        'surface-dim': '#dad6f8',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed-variant': '#653e00',
        'surface-container-low': '#f6f2ff',
        'on-secondary-fixed': '#2a1700',
        'on-error': '#ffffff',
        'primary-container': '#6c5ce7',
        'surface-container-high': '#e9e5ff',
        'inverse-primary': '#c6bfff',
        'outline-variant': '#c8c4d7',
        'surface-container': '#efebff',
        'on-surface': '#1a1931',
        'surface-container-highest': '#e3dfff',
        'on-primary-fixed-variant': '#4029ba',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffddb8',
        tertiary: '#006645',
        secondary: '#855300',
        'on-primary-fixed': '#160066',
        'tertiary-container': '#008259',
        'primary-fixed-dim': '#c6bfff',
        'on-tertiary-fixed-variant': '#005236',
        'secondary-fixed-dim': '#ffb95f',
        ink: {
          DEFAULT: '#12112A',
          rail: '#1C1A3A',
          hover: '#25224D',
          border: '#1F1E3D',
          muted: '#A0AEC0',
        },
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        margin: '2rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        'space-xl': '2.25rem',
        'gutter-sm': '1rem',
        'space-lg': '1.5rem',
        'margin-sm': '1rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"'],
        'label-lg': ['"Plus Jakarta Sans"'],
        'label-caps': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'display-hero': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'body-sm': ['"Plus Jakarta Sans"'],
        'stat-counter': ['"Plus Jakarta Sans"'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '500' }],
        'stat-counter': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
